# Generated by Django 4.2.4 on 2023-08-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='organisation',
            name='tenantawaremodels_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer1.tenantawaremodels'),
            preserve_default=False,
        ),
    ]
