# Generated by Django 4.2.4 on 2023-08-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer1', '0002_remove_organisation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantawaremodels',
            old_name='tanent',
            new_name='tenant',
        ),
    ]
